library(ggplot2)
library(RColorBrewer)
library(gdata)
library(gtools) 
library(RgoogleMaps)
library(ggmap)   
library(plyr)
library(dplyr)
library(car)
library(reports)
library(tidyr)
library(reshape2)
library(FD)

#install.packages("FD")
